#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_USE_IRQ) += interrupts.o
obj-$(CONFIG_DISPLAY_CPUINFO)	+= cpu_info.o
obj-y	+= speed.o
obj-y	+= timer.o
obj-y   += i2c.o
obj-y   += serial.o
obj-y   += usb.o
obj-y   += usb_ohci.o
obj-y   += nand_read.o
obj-y   += nand.o
obj-y   += cmd_s3c24xx.o
obj-y   += mmc.o
